// Sample data for the application

export const sampleProperties = [
  {
    id: '1',
    name: 'Sunset Apartments',
    address: '123 Oak Street',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90001',
    units: 8,
    type: 'residential',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
    monthlyRevenue: 8400,
    occupancy: 100,
    status: 'active',
  },
  {
    id: '2',
    name: 'Downtown Office Complex',
    address: '456 Main Ave',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90002',
    units: 12,
    type: 'commercial',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=300&fit=crop',
    monthlyRevenue: 15600,
    occupancy: 92,
    status: 'active',
  },
  {
    id: '3',
    name: 'Beachside Villa',
    address: '789 Coast Road',
    city: 'Malibu',
    state: 'CA',
    zip: '90265',
    units: 4,
    type: 'residential',
    image: 'https://images.unsplash.com/photo-1523217311519-f0a14e172e28?w=400&h=300&fit=crop',
    monthlyRevenue: 6000,
    occupancy: 75,
    status: 'active',
  },
  {
    id: '4',
    name: 'Mountain Lodge',
    address: '321 Peak Lane',
    city: 'Big Bear',
    state: 'CA',
    zip: '92314',
    units: 6,
    type: 'residential',
    image: 'https://images.unsplash.com/photo-1578458979293-cb54fc248ae0?w=400&h=300&fit=crop',
    monthlyRevenue: 4800,
    occupancy: 67,
    status: 'active',
  },
  {
    id: '5',
    name: 'Urban Lofts',
    address: '555 Broadway',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90003',
    units: 10,
    type: 'residential',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
    monthlyRevenue: 9500,
    occupancy: 80,
    status: 'active',
  },
]

export const sampleTenants = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '555-0101',
    propertyId: '1',
    unit: 'A1',
    rentAmount: 1200,
    leaseStart: '2023-01-15',
    leaseEnd: '2025-01-14',
    status: 'current',
    balance: 0,
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '555-0102',
    propertyId: '1',
    unit: 'A2',
    rentAmount: 1200,
    leaseStart: '2023-06-01',
    leaseEnd: '2025-05-31',
    status: 'current',
    balance: 0,
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael@example.com',
    phone: '555-0103',
    propertyId: '2',
    unit: 'B1',
    rentAmount: 1500,
    leaseStart: '2023-03-01',
    leaseEnd: '2025-02-28',
    status: 'current',
    balance: 1500,
  },
  {
    id: '4',
    name: 'Emily Wilson',
    email: 'emily@example.com',
    phone: '555-0104',
    propertyId: '2',
    unit: 'B2',
    rentAmount: 1500,
    leaseStart: '2023-08-15',
    leaseEnd: '2024-08-14',
    status: 'moving-out',
    balance: 0,
  },
  {
    id: '5',
    name: 'David Brown',
    email: 'david@example.com',
    phone: '555-0105',
    propertyId: '3',
    unit: 'C1',
    rentAmount: 1500,
    leaseStart: '2023-02-01',
    leaseEnd: '2025-01-31',
    status: 'current',
    balance: 0,
  },
  {
    id: '6',
    name: 'Jessica Martinez',
    email: 'jessica@example.com',
    phone: '555-0106',
    propertyId: '3',
    unit: 'C2',
    rentAmount: 1500,
    leaseStart: '2023-07-01',
    leaseEnd: '2025-06-30',
    status: 'current',
    balance: 3000,
  },
  {
    id: '7',
    name: 'Robert Taylor',
    email: 'robert@example.com',
    phone: '555-0107',
    propertyId: '4',
    unit: 'D1',
    rentAmount: 800,
    leaseStart: '2023-09-01',
    leaseEnd: '2025-08-31',
    status: 'current',
    balance: 0,
  },
  {
    id: '8',
    name: 'Lisa Anderson',
    email: 'lisa@example.com',
    phone: '555-0108',
    propertyId: '5',
    unit: 'E1',
    rentAmount: 950,
    leaseStart: '2023-04-15',
    leaseEnd: '2025-04-14',
    status: 'current',
    balance: 0,
  },
  {
    id: '9',
    name: 'James Thomas',
    email: 'james@example.com',
    phone: '555-0109',
    propertyId: '5',
    unit: 'E2',
    rentAmount: 950,
    leaseStart: '2023-05-01',
    leaseEnd: '2025-04-30',
    status: 'current',
    balance: 950,
  },
  {
    id: '10',
    name: 'Amanda White',
    email: 'amanda@example.com',
    phone: '555-0110',
    propertyId: '1',
    unit: 'A3',
    rentAmount: 1200,
    leaseStart: '2023-11-01',
    leaseEnd: '2025-10-31',
    status: 'current',
    balance: 0,
  },
]

export const sampleTransactions = [
  { id: '1', type: 'payment', amount: 1200, date: '2024-02-05', tenant: 'John Smith', property: 'Sunset Apartments', status: 'completed' },
  { id: '2', type: 'expense', amount: 350, date: '2024-02-04', description: 'Plumbing repair', property: 'Sunset Apartments', status: 'completed' },
  { id: '3', type: 'payment', amount: 1500, date: '2024-02-03', tenant: 'Michael Chen', property: 'Downtown Office Complex', status: 'pending' },
  { id: '4', type: 'expense', amount: 1200, date: '2024-02-02', description: 'HVAC maintenance', property: 'Downtown Office Complex', status: 'completed' },
  { id: '5', type: 'payment', amount: 1500, date: '2024-02-01', tenant: 'David Brown', property: 'Beachside Villa', status: 'completed' },
  { id: '6', type: 'expense', amount: 500, date: '2024-01-31', description: 'Landscaping', property: 'Beachside Villa', status: 'completed' },
  { id: '7', type: 'payment', amount: 800, date: '2024-01-30', tenant: 'Robert Taylor', property: 'Mountain Lodge', status: 'completed' },
  { id: '8', type: 'expense', amount: 200, date: '2024-01-29', description: 'Cleaning supplies', property: 'Mountain Lodge', status: 'completed' },
  { id: '9', type: 'payment', amount: 950, date: '2024-01-28', tenant: 'Lisa Anderson', property: 'Urban Lofts', status: 'completed' },
  { id: '10', type: 'expense', amount: 750, date: '2024-01-27', description: 'Property insurance', property: 'Urban Lofts', status: 'completed' },
  { id: '11', type: 'payment', amount: 1200, date: '2024-01-26', tenant: 'Sarah Johnson', property: 'Sunset Apartments', status: 'completed' },
  { id: '12', type: 'expense', amount: 300, date: '2024-01-25', description: 'Pest control', property: 'Sunset Apartments', status: 'completed' },
  { id: '13', type: 'payment', amount: 1500, date: '2024-01-24', tenant: 'Emily Wilson', property: 'Downtown Office Complex', status: 'completed' },
  { id: '14', type: 'expense', amount: 1500, date: '2024-01-23', description: 'Roof repair', property: 'Downtown Office Complex', status: 'completed' },
  { id: '15', type: 'payment', amount: 1500, date: '2024-01-22', tenant: 'Jessica Martinez', property: 'Beachside Villa', status: 'pending' },
  { id: '16', type: 'expense', amount: 400, date: '2024-01-21', description: 'Painting', property: 'Beachside Villa', status: 'completed' },
  { id: '17', type: 'payment', amount: 950, date: '2024-01-20', tenant: 'James Thomas', property: 'Urban Lofts', status: 'pending' },
  { id: '18', type: 'expense', amount: 600, date: '2024-01-19', description: 'Flooring repair', property: 'Urban Lofts', status: 'completed' },
  { id: '19', type: 'payment', amount: 1200, date: '2024-01-18', tenant: 'Amanda White', property: 'Sunset Apartments', status: 'completed' },
  { id: '20', type: 'expense', amount: 250, date: '2024-01-17', description: 'Light fixtures', property: 'Sunset Apartments', status: 'completed' },
]

export const sampleMaintenanceRequests = [
  {
    id: '1',
    property: 'Sunset Apartments',
    unit: 'A1',
    tenant: 'John Smith',
    description: 'Leaky faucet in kitchen',
    priority: 'high',
    status: 'assigned',
    createdDate: '2024-02-05',
    assignedTo: 'John\'s Plumbing',
    estimatedCost: 150,
  },
  {
    id: '2',
    property: 'Downtown Office Complex',
    unit: 'B3',
    tenant: 'Unknown',
    description: 'AC unit not cooling',
    priority: 'high',
    status: 'in-progress',
    createdDate: '2024-02-04',
    assignedTo: 'Cool Air Services',
    estimatedCost: 500,
  },
  {
    id: '3',
    property: 'Beachside Villa',
    unit: 'C1',
    tenant: 'David Brown',
    description: 'Broken window latch',
    priority: 'medium',
    status: 'requested',
    createdDate: '2024-02-03',
    assignedTo: null,
    estimatedCost: 200,
  },
  {
    id: '4',
    property: 'Urban Lofts',
    unit: 'E2',
    tenant: 'James Thomas',
    description: 'Door hinge broken',
    priority: 'low',
    status: 'completed',
    createdDate: '2024-01-28',
    assignedTo: 'General Maintenance',
    estimatedCost: 75,
  },
  {
    id: '5',
    property: 'Mountain Lodge',
    unit: 'D2',
    tenant: 'Unknown',
    description: 'Weatherstripping needed',
    priority: 'low',
    status: 'completed',
    createdDate: '2024-01-20',
    assignedTo: 'Weather Seal Inc',
    estimatedCost: 300,
  },
  {
    id: '6',
    property: 'Sunset Apartments',
    unit: 'A4',
    tenant: 'Unknown',
    description: 'Ceiling water damage',
    priority: 'high',
    status: 'in-progress',
    createdDate: '2024-02-02',
    assignedTo: 'Pro Restoration',
    estimatedCost: 1200,
  },
  {
    id: '7',
    property: 'Downtown Office Complex',
    unit: 'B1',
    tenant: 'Michael Chen',
    description: 'Carpet stain cleaning',
    priority: 'low',
    status: 'requested',
    createdDate: '2024-02-01',
    assignedTo: null,
    estimatedCost: 300,
  },
  {
    id: '8',
    property: 'Urban Lofts',
    unit: 'E5',
    tenant: 'Unknown',
    description: 'Paint touch-up needed',
    priority: 'low',
    status: 'requested',
    createdDate: '2024-01-31',
    assignedTo: null,
    estimatedCost: 250,
  },
]

export const sampleVendors = [
  {
    id: '1',
    name: 'John\'s Plumbing',
    category: 'Plumbing',
    rating: 4.8,
    reviews: 24,
    phone: '555-1001',
    email: 'contact@johnsplumbing.com',
    responseTime: '2 hours',
  },
  {
    id: '2',
    name: 'Cool Air Services',
    category: 'HVAC',
    rating: 4.6,
    reviews: 18,
    phone: '555-1002',
    email: 'support@coolairservices.com',
    responseTime: '4 hours',
  },
  {
    id: '3',
    name: 'General Maintenance',
    category: 'General',
    rating: 4.5,
    reviews: 31,
    phone: '555-1003',
    email: 'hello@genmaintenance.com',
    responseTime: '6 hours',
  },
  {
    id: '4',
    name: 'Pro Restoration',
    category: 'Restoration',
    rating: 4.9,
    reviews: 15,
    phone: '555-1004',
    email: 'info@prorestoration.com',
    responseTime: '1 hour',
  },
]

export const chartData = [
  { month: 'Jan', revenue: 28000, expenses: 8400 },
  { month: 'Feb', revenue: 32000, expenses: 9200 },
  { month: 'Mar', revenue: 29500, expenses: 8800 },
  { month: 'Apr', revenue: 35000, expenses: 10200 },
  { month: 'May', revenue: 38000, expenses: 10500 },
  { month: 'Jun', revenue: 40200, expenses: 11000 },
  { month: 'Jul', revenue: 39800, expenses: 10800 },
  { month: 'Aug', revenue: 42000, expenses: 11200 },
  { month: 'Sep', revenue: 41500, expenses: 11000 },
  { month: 'Oct', revenue: 43200, expenses: 11500 },
  { month: 'Nov', revenue: 45000, expenses: 12000 },
  { month: 'Dec', revenue: 48000, expenses: 12500 },
]

export const expenseBreakdown = [
  { name: 'Maintenance', value: 35, fill: '#0d47a1' },
  { name: 'Utilities', value: 25, fill: '#1976d2' },
  { name: 'Insurance', value: 20, fill: '#42a5f5' },
  { name: 'Taxes', value: 15, fill: '#64b5f6' },
  { name: 'Other', value: 5, fill: '#bbdefb' },
]

export const occupancyData = [
  { property: 'Sunset Apt', occupancy: 100 },
  { property: 'Downtown Office', occupancy: 92 },
  { property: 'Beachside Villa', occupancy: 75 },
  { property: 'Mountain Lodge', occupancy: 67 },
  { property: 'Urban Lofts', occupancy: 80 },
]
