// Tenant-specific sample data

export const currentTenant = {
  id: 'tenant-001',
  name: 'Sarah Anderson',
  email: 'sarah.anderson@email.com',
  phone: '+1 (555) 234-5678',
  propertyId: '1',
  unit: '2B',
  leaseStart: '2023-01-15',
  leaseEnd: '2025-01-14',
  monthlyRent: 1200,
  status: 'active',
  moveInDate: '2023-01-15',
}

export const paymentHistory = [
  {
    id: 'pay-001',
    amount: 1200,
    date: '2024-01-05',
    status: 'paid',
    dueDate: '2024-01-01',
    method: 'Bank Transfer',
  },
  {
    id: 'pay-002',
    amount: 1200,
    date: '2024-02-03',
    status: 'paid',
    dueDate: '2024-02-01',
    method: 'Credit Card',
  },
  {
    id: 'pay-003',
    amount: 1200,
    date: '2024-03-08',
    status: 'paid',
    dueDate: '2024-03-01',
    method: 'Bank Transfer',
  },
  {
    id: 'pay-004',
    amount: 1200,
    date: '2024-04-02',
    status: 'paid',
    dueDate: '2024-04-01',
    method: 'Check',
  },
  {
    id: 'pay-005',
    amount: 1200,
    date: '2024-05-06',
    status: 'paid',
    dueDate: '2024-05-01',
    method: 'Bank Transfer',
  },
  {
    id: 'pay-006',
    amount: 1200,
    date: '2024-06-01',
    status: 'paid',
    dueDate: '2024-06-01',
    method: 'Bank Transfer',
  },
  {
    id: 'pay-007',
    amount: 1200,
    date: null,
    status: 'pending',
    dueDate: '2024-07-01',
    method: null,
  },
]

export const maintenanceRequests = [
  {
    id: 'maint-001',
    title: 'Leaky Kitchen Faucet',
    description: 'The kitchen faucet has been dripping for about a week now',
    status: 'resolved',
    priority: 'medium',
    date: '2024-02-15',
    resolvedDate: '2024-02-18',
    category: 'plumbing',
  },
  {
    id: 'maint-002',
    title: 'Bathroom Light Fixture',
    description: 'Light in master bathroom keeps flickering',
    status: 'in-progress',
    priority: 'medium',
    date: '2024-05-20',
    resolvedDate: null,
    category: 'electrical',
  },
  {
    id: 'maint-003',
    title: 'AC Unit Not Cooling',
    description: 'Air conditioning unit is running but not cooling the apartment',
    status: 'assigned',
    priority: 'high',
    date: '2024-06-10',
    resolvedDate: null,
    category: 'hvac',
  },
  {
    id: 'maint-004',
    title: 'Door Lock Issue',
    description: 'Front door lock is sticking slightly',
    status: 'pending',
    priority: 'low',
    date: '2024-06-25',
    resolvedDate: null,
    category: 'locks',
  },
]

export const notifications = [
  {
    id: 'notif-001',
    title: 'Rent Due Reminder',
    message: 'Your rent payment for July is due on July 1st',
    type: 'payment',
    date: '2024-06-25',
    read: false,
    actionUrl: '/tenant/payments',
  },
  {
    id: 'notif-002',
    title: 'Maintenance Request Assigned',
    message: 'Your AC unit maintenance request has been assigned to a technician',
    type: 'maintenance',
    date: '2024-06-24',
    read: false,
    actionUrl: '/tenant/maintenance',
  },
  {
    id: 'notif-003',
    title: 'Payment Received',
    message: 'Your June rent payment of $1,200 has been received',
    type: 'payment',
    date: '2024-06-01',
    read: true,
    actionUrl: '/tenant/payments',
  },
  {
    id: 'notif-004',
    title: 'Maintenance Completed',
    message: 'Your kitchen faucet repair has been completed',
    type: 'maintenance',
    date: '2024-02-18',
    read: true,
    actionUrl: '/tenant/maintenance',
  },
  {
    id: 'notif-005',
    title: 'Important Notice',
    message: 'Please check your mailbox for the lease renewal form',
    type: 'general',
    date: '2024-05-15',
    read: true,
    actionUrl: '/tenant/messages',
  },
]

export const managementContacts = [
  {
    id: 'contact-001',
    name: 'John Mitchell',
    title: 'Property Manager',
    email: 'john.mitchell@propmanager.com',
    phone: '+1 (555) 123-4567',
    hours: 'Monday - Friday, 9AM - 5PM',
  },
  {
    id: 'contact-002',
    name: 'Emergency Maintenance',
    title: 'After-Hours Support',
    email: null,
    phone: '+1 (555) 123-4568',
    hours: 'Available 24/7 for emergencies',
  },
  {
    id: 'contact-003',
    name: 'Leasing Office',
    title: 'Leasing & Inquiries',
    email: 'leasing@propmanager.com',
    phone: '+1 (555) 123-4569',
    hours: 'Monday - Saturday, 10AM - 6PM',
  },
]

export const propertyInfo = {
  name: 'Sunset Apartments',
  address: '123 Oak Street',
  city: 'Los Angeles',
  state: 'CA',
  zip: '90001',
  image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
}
